language: python
python: 3.7

dist: xenial

install:
  - pip install tox

matrix:
  include:
    - stage: test
      python: 2.7
      env: TOX_ENV="py27-nameko{2.9,2.10,2.11,2.12,latest}"

    - stage: test
      python: 3.5
      env: TOX_ENV="py35-nameko{2.7,2.8,2.9,2.10,2.11,2.12,latest}"

    - stage: test
      python: 3.6
      env: TOX_ENV="py36-nameko{2.7,2.8,2.9,2.10,2.11,2.12,latest}"

    - stage: test
      python: 3.7
      env: TOX_ENV="py37-nameko{2.7,2.8,2.9,2.10,2.11,2.12,latest}"

script:
  - tox -e $TOX_ENV
